<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php $form = $this->editForm ?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="courier">Доставка</div>
            <div class="tab" data-tab="pickup">Самовывоз</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->AdminFormRow($form->get('courier_company'));
                echo $this->AdminFormRow($form->get('region_id'));
                echo $this->AdminFormRow($form->get('name'));
                echo $this->AdminFormRow($form->get('delay'));
                echo $this->AdminFormRow($form->get('delay_text'));
                ?>
            </div>
            <div class="tab" data-tab="pickup">
                <?php
                echo $this->AdminFormRow($form->get('pickup_income'));
                echo $this->AdminFormRow($form->get('pickup_outgo'));
                echo $this->AdminFormRow($form->get('pickup_free'));
                echo $this->AdminFormRow($form->get('pickup_text'));
                ?>
            </div>
            <div class="tab" data-tab="courier">
                <?php
                echo $this->AdminFormRow($form->get('courier_income'));
                echo $this->AdminFormRow($form->get('courier_outgo'));
                echo $this->AdminFormRow($form->get('courier_free'));
                echo $this->AdminFormRow($form->get('delivery_text'));
                ?>
            </div>
        </div>
    </div>

    <script>
        var form = $('.edit-form');

        var regionId = $('[name="region_id"]', form);
        var regionNa = $('[name="name"]', form);

        regionId.on('change', function () {
            regionNa.val(regionId.find('option[value="' + regionId.val() + '"]').text());
        });
    </script>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>