<div class="error-page">
    <div class="pic"><img src="/images/404/longcat.jpg"></div>
    <div class="txt">
        <div class="code">404</div>
        страница не найдена
    </div>
</div>
<style>
    .error-page {
        height: 500px;
        position: relative;
        padding-left: 50%;
    }

    .error-page .pic {
        position: absolute;
        bottom: 0;
        left: 0;
        max-width: 50%;
    }

    .error-page {

    }

    .error-page {

    }

    .error-page {

    }
</style>
