<div class="order-st-popup">
    <form action="/order/order-status/" class="std-form">
        <div class="title">Введите номер заказа</div>
        <div class="row">
            <input type="text" name="id" class="std-input nbr">
        </div>
        <input type="submit" value="Найти заказ" class="btn">
    </form>
    <div class="info"></div>

    <script>
        var box = $('.order-st-popup');
        var info = $('.info', box);
        var form = $('form', box);

        $('.nbr', form).inputmask('347-9999');
        
        form.formSubmit({
            success: function (resp) {
                form.css({display: 'none'});
                info.append(resp.html).fadeIn(200);
            }
        });
    </script>

    <style>
        .order-st-popup {
            width: 445px;
            padding: 32px 45px;
        }

        .order-st-popup form {
            max-width: 290px;
            margin: 0 auto;
        }

        .order-st-popup form .nbr {
            text-align: center;
        }

        .order-st-popup form .nbr,
        .order-st-popup form .btn {
            width: 100%;
        }

        .order-st-popup form .title {
            font-size: 18px;
            text-align: center;
            margin-bottom: 16px;
        }

        .order-st-popup .info .header {
            font-size: 20px;
            margin-bottom: 14px;
            text-align: center;
        }

        .order-st-popup .info .sum {
            padding: 12px 20px;
            background: #f5f5f5;
            margin-bottom: 20px;
            font-size: 15px;
            text-align: center;
        }

        .order-st-popup .info .sum a {
            color: #0060c1;
            text-decoration: underline;
            font-size: 14px;
        }

        .order-st-popup .info .status {
            text-align: center;
        }

        .order-st-popup .info .status .title {
            text-align: center;
            margin-bottom: 10px;
            font-weight: bold;
            font-size: 18px;
        }

        .order-st-popup .info .price {
            margin-top: 12px;
            font-weight: 600;
        }

        .order-st-popup .info {

        }

        .order-st-popup .info .btn {
            width: 180px;
            display: block;
            margin: 24px auto 0 auto;
        }

        @media all and (max-width: 520px) {
            .order-st-popup {
                width: auto;
                padding: 32px 15px;
            }

            .order-st-popup .info .sum {
                padding: 12px 20px;
            }
        }
    </style>
</div>