<form method="POST" action="https://money.yandex.ru/quickpay/confirm.xml">
    <input type="hidden" name="receiver" value="410011137806564">
    <input type="hidden" name="formcomment" value="Olympic Trade: заказ №123">
    <input type="hidden" name="short-dest" value="Olympic Trade: заказ №123">
    <input type="hidden" name="label" value="123">
    <input type="hidden" name="quickpay-form" value="shop">
    <input type="hidden" name="targets" value="Оплата заказа №123">
    <input type="hidden" name="sum" value="4">
    <input type="hidden" name="label" value="123">
    <input type="hidden" name="comment" value="Хотелось бы параллельной флюкабельности.">
    <input type="radio" name="paymentType" value="PC">Яндекс.Деньгами</input>
    <?php /*<input type="radio" name="paymentType" value="AC">Банковской картой</input>*/ ?>
    <input type="submit" name="submit-button" value="Перевести">
</form>