<?php
$inStock = '';
$notInStock = '';
if($product->get('stock')) {
    $inStock = ' style="display: block"';
} else {
    $notInStock = ' style="display: block"';
}

$images = $product->getPlugin('images')->load();
$attrs = $product->getPlugin('attrs');
?>

<div class="product-popup">
    <div class="product">
        <div class="images<?php echo $images ? ' gl' : '' ?>">
            <?php
            $html = '<div class="thumbs">';

            if(!$images->count()) {
                $html .=
                    '<a href="' . $product->getPlugin('image')->getImage('m') . '" data-zoom="' . $product->getPlugin('image')->getImage('hr') . '" class="thumb hide">'
                    .'<img src="' . $product->getPlugin('image')->getImage('s') . '">'
                    .'</a>';
            } else {
                foreach ($product->getPlugin('images')->load() as $image) {
                    $html .=
                        '<a href="' . $image->getImage('m') . '" class="thumb hide" data-zoom="' . $image->getImage('hr') . '" data-taste="' . $image->get('taste_id') . '" data-size="' . $image->get('size_id') . '">'
                        .'<img src="' . $image->getImage('s') . '">'
                        .'</a>';
                }
            }

            $html .=
                '</div>';

            echo $html;
            ?>

            <div class="pic hide" data-taste="" data-size="">
                <img src="<?php echo $product->getPlugin('image')->getImage('m'); ?>" data-zoom-image="" alt="<?php echo $product->get('name'); ?>">
            </div>

            <?php echo $eventsHtml ?>
        </div>

        <div class="info">
            <div class="name"><?php echo $product->get('name') ?></div>
            <div class="type-box">
                <div class="props-box">
                    <input type="hidden" value="<?php echo $product->getId() ?>" name="product_id">

                    <?php
                    $propName1 = $attrs->get('prop_name_1') ? $attrs->get('prop_name_1') : 'Размер';
                    echo $this->cartTypeBoxSelect('size_id', $product->getPlugin('size'), $propName1);

                    $propName2 = $attrs->get('prop_name_2') ? $attrs->get('prop_name_2') : 'Вкус';
                    echo$this->cartTypeBoxSelect('taste_id', $product->getPlugin('taste'), $propName2);
                    ?>

                    <div class="row row-counter">
                        <div class="label">Кол-во</div>
                        <div class="std-counter m">
                            <input value="1" min="1" max="999" name="count" class="js-count">
                            <div class="incr"></div>
                            <div class="decr"></div>
                        </div>
                    </div>
                </div>

                <div class="price-box">
                    <span class="price"><span><?php echo $this->price($product->get('price')) ?></span> <i class="fa fa-ruble-sign"></i></span>
                    <?php if($product->get('discount')) { ?>
                        <span class="price-old"><span><?php echo $this->price($product->get('price_old')) ?></span> <i class="fa fa-ruble-sign"></i></span>
                    <?php } ?>

                    <div class="btns"<?php echo $inStock ?>>
                        <a href="/cart/" class="btn stock-i cart-add js-cart-add"><span>В корзину</span></a>
                        <span class="btn blue stock-o request-add js-request-add">Предзаказ<span>(Без предоплаты)</span></span>
                        <div class="clear"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="clear"></div>

    <?php include('product-tabs.phtml') ?>

    <div class="clear"></div>
</div>