<?php echo $this->header() ?>

<?php
$imgSize = $this->isMobile() ? 's' : 'm';
?>
<div class="block blog-view">
    <div class="wrapper">
            <div class="cb-image">
                <img src="<?php echo $article->getPlugin('image')->getImage($imgSize) ?>" alt="<?php echo $article->get('name') ?>">
            </div>
            <?php echo $this->contentRender($article->getPlugin('content')) ?>

            <?php /*
            <div class="tags">
                <div class="label">Теги</div>
                <?php
                $html = '';
                foreach(explode(',', $article->get('tags')) as $tag) {
                    $html .= ', <a href="/blog/search/?query=' . $tag . '">' . trim($tag) . '</a>';
                }
                echo ltrim($html, ', ');
                ?>
            </div>
            */ ?>

            <div class="comments">
                <div class="summary">
                    <span class="btn add-comment popup" href="/blog/add-comment/?aid=<?php echo $article->getId() ?>">Добавить комментарий</span>
                </div>
                <div class="list">
                    <?php echo $this->articlesComments($article, $article->getPlugin('comments')) ?>
                </div>
            </div>
        <div class="clear"></div>
    </div>
</div>