<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php
$form = $this->editForm;
$request = $this->model;
?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->AdminFormRow($form->get('contact'));
                $productUrl = $this->url('adminProducts', array('action' => 'edit')) . '?id=' . $request->getPlugin('product')->getId();
                ?>
                <div class="row">
                    <div class="label">Товар</div>
                    <a href="<?php echo $productUrl ?>"><?php echo $request->getPlugin('product')->get('name'); ?></a>
                </div>
                <div class="row">
                    <div class="label">Размер</div>
                    <?php echo $request->getPlugin('price')->get('name'); ?>
                </div>
                <div class="row">
                    <div class="label">Вкус</div>
                    <?php echo $request->getPlugin('taste')->get('name'); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>