<div class="popup-wiki-calc wiki-calc">
    <div class="calc">
        <h1 class="title">Калькулятор питания</h1>
        <div class="row">
            <div class="label">Пол:</div>
            <select name="gender" class="std-select">
                <option value="1">Мужчина</option>
                <option value="2">Женщина</option>
            </select>
        </div>

        <div class="row">
            <div class="label">Возвраст:</div>
            <select name="age" class="std-select">
                <option value="1">0-8 лет</option>
                <option value="2">8-16 лет</option>
                <option value="3">16-32 лет</option>
            </select>
        </div>

        <div class="row">
            <div class="label">Спорт:</div>
            <select name="sport" class="std-select">
                <option value="1">Не занимаюсь</option>
                <option value="2">5 часов в неделю</option>
                <option value="3">10 часов в неделю</option>
                <option value="3">15 часов в неделю</option>
                <option value="3">20 часов в неделю</option>
            </select>
        </div>

        <div class="row">
            <div class="label">Вес:</div>
            <select name="weight" class="std-select">
                <option value="1">40 - 60 кг</option>
                <option value="2">60 - 80 кг</option>
                <option value="3">80 - 100 кг</option>
            </select>
        </div>

        <div class="row">
            <div class="label">Цель:</div>
            <select name="target" class="std-select">
                <option value="1">Сбросить вес</option>
                <option value="2">Набрать мышц</option>
                <option value="3">Сохранить вес</option>
            </select>
        </div>
    </div>
    <div class="result">
        <h2 class="title">Дневная норма</h2>
        <div class="notice">
            <span>*</span> Нажмите на элемент, чтобы узнать подробную информацию о немю
        </div>

        <div class="table"></div>
    </div>
    <div class="clean"></div>

    <script>
        var box = $('.wiki-calc');
        var calc = $('.calc', box);
        var result = $('.result', box);

        calc.css({minHeight: result.innerHeight()});

        $('input, select', calc).on('change', function () {
            $.ajax({
                url: '/wiki/calc/',
                method: 'post',
                data: $.aptero.serializeArray(calc),
                success: function(resp) {
                    $('.table', result).html(resp.html);
                },
            });
        });
    </script>

    <style>
        .popup-wiki-calc {
            width: 630px;
            padding: 15px 20px;
        }

        .wiki-calc .calc,
        .wiki-calc .result {
            float: left;
            width: 46%;
            padding-bottom: 30px;
        }

        .wiki-calc .calc {
            padding-right: 4%;
            margin-right: 4%;
            border-right: 1px solid #909090;
        }

        .wiki-calc .calc .row {
            position: relative;
            padding-left: 75px;
            margin-bottom: 10px;
        }

        .wiki-calc .calc .row .label {
            width: 65px;
            position: absolute;
            left: 0;
            top: 9px;
        }

        .wiki-calc .calc .row select {
            height: 38px;
        }

        .wiki-calc .result .notice {
            font-size: 13px;
            margin-bottom: 13px;
        }

        .wiki-calc .result .notice span {
            color: #ed5917;
        }

        .wiki-calc .result .key,
        .wiki-calc .result .val {
            border-bottom: 1px solid #b3b3b3;
            padding: 3px 0;
        }

        .wiki-calc .result tr:hover td {
            background: #f2f2f2;
        }

        .wiki-calc .result .key {
            padding-right: 20px;
            width: 150px;
        }

        .wiki-calc .result th {
            padding: 15px 0 12px 0;
            font-weight: bold;
        }

        .wiki-calc .title {
            font-size: 18px;
            margin-bottom: 10px;
        }
    </style>
</div>