<div class="popup-wiki-el">
    <h1><?php echo $element->get('name') ?></h1>

    <div class="std-text">
        <?php echo $element->get('text') ?>
    </div>

    <style>
        .popup-wiki-el {
            padding: 20px 30px;
            width: 800px;
        }

        .popup-wiki-el h1 {
            font-size: 30px;
            margin-bottom: 20px;
        }

        .popup-wiki-el {

        }
    </style>
</div>