<?php echo $this->header(['header' => '']) ?>

<div class="block">
    <div class="wrapper">
        <a href="/wiki/calc/" class="popup">Калькулятор</a>
        <div class="wiki-menu">
            <div class="col">
                <div class="box">
                    <div class="header">Витамины</div>
                    <div class="body circles">
                        <a href="/wiki/vitamin-a/" class="row popup">A</a>
                        <div class="row">B1</div>
                        <div class="row">B2</div>
                        <div class="row">B3</div>
                        <div class="row">B6</div>
                        <div class="row">B12</div>
                        <div class="row">C</div>
                        <div class="row">D</div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="box">
                    <div class="header">Минералы</div>
                    <div class="body circles">
                        <div class="row">A</div>
                        <div class="row">B1</div>
                        <div class="row">B2</div>
                        <div class="row">B3</div>
                        <div class="row">B6</div>
                        <div class="row">B12</div>
                        <div class="row">C</div>
                        <div class="row">D</div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="box box-protein">
                    <div class="header">Белки</div>
                    <div class="body list">
                        <div class="row">Гистедин</div>
                        <div class="row">Изолейцин</div>
                        <div class="row">Лейцин</div>
                        <div class="row">Лизин</div>
                        <div class="row">Метионин</div>
                        <div class="row">Фенилаланин</div>
                        <div class="row">Гистедин</div>
                        <div class="row">Изолейцин</div>
                        <div class="row">Лейцин</div>
                        <div class="row">Лизин</div>
                        <div class="row">Метионин</div>
                        <div class="row">Фенилаланин</div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="box">
                    <div class="header">Жиры</div>
                    <div class="body list">
                        <div class="row">Животные жиры</div>
                        <div class="row">Ростительные жиры</div>
                        <div class="row">Холестерин</div>
                        <div class="row">Омега 3/6/9</div>
                    </div>
                </div>
                <div class="box">
                    <div class="header">Углеводы</div>
                    <div class="body list">
                        <div class="row">Медленные углеводы</div>
                        <div class="row">Быстрые углеводы</div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

<style>
    .wiki-menu {
        margin-bottom: 80px;
    }

    .wiki-menu .col {
        width: 25%;
        margin-right: 2%;
        border: 1px solid #cccccc;
        padding: 15px 20px;
        float: left;
    }

    .wiki-menu .box {
        margin-top: 20px;
    }

    .wiki-menu .header {
        font-size: 22px;
        margin-bottom: 12px;
    }

    .wiki-menu .box:first-child {
        margin-top: 0;
    }

    .wiki-menu .list .row {
        margin-bottom: 4px;
    }

    .wiki-menu .box-protein .list .row {
        float: left;
        width: 50%;
        font-style: italic;
    }

    .wiki-menu .circles .row {
        border: 2px solid #ee7923;
        border-radius: 50%;
        width: 42px;
        line-height: 38px;
        text-align: center;
        font-size: 14px;
        float: left;
        margin: 0 10px 10px 0;
    }

    .wiki-menu {

    }

    .wiki-menu {

    }
</style>