<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('section') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php $form = $this->editForm ?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="items">Пункты меню</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->AdminFormRow($form->get('name'));
                echo $this->AdminFormRow($form->get('position'));
                ?>
            </div>
            <div class="tab" data-tab="items">
                <?php if($this->model->getId()) { ?>
                <?php
                $addUrl = $this->url('adminMenuItems', array(
                    'action' => 'edit'
                ), array(
                    'query' => array('menu' => $this->model->getId())
                ));
                ?>

                <?php echo $this->adminTableList($this->menuItemsFields, $this->menuItems, array('module' => 'application', 'section' => 'menu-items')); ?>
                <div style="margin-top: 10px;">
                    <a href="<?php echo $addUrl ?>" class="btn btn-blue">Добавить</a>
                </div>
                <?php } else { ?>
                <div class="notice">
                    Возможность дабавления пунктов появится после сохранения меню
                </div>
                <?php } ?>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
        <a class="btn btn-red btn-remove-ck" href="#popup-delete">
            <i class="fa fa-times"></i>
            Удалить
        </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>
