<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php $form = $this->editForm ?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="contacts">Контакты</div>
            <div class="tab" data-tab="access">Доступ</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->AdminFormRow($form->get('image-image'));
                echo $this->AdminFormRow($form->get('name'));
                ?>
            </div>
            <div class="tab" data-tab="contacts">
                <?php
                echo $this->AdminFormRow($form->get('attrs-contact'));
                echo $this->AdminFormRow($form->get('email'));
                echo $this->AdminFormRow($form->get('attrs-phone'));
                echo $this->AdminFormRow($form->get('attrs-skype'));
                ?>
            </div>
            <div class="tab" data-tab="access">
                <?php
                echo $this->AdminFormRow($form->get('password'));
                echo $this->AdminFormRow($form->get('password_repeat'));
                echo $this->AdminFormRow($form->get('type'));
                echo $this->AdminFormRow($form->get('active'));
                echo $this->AdminFormRow($form->get('confirm'));
                ?>
            </div>
        </div>
    </div>
    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>