<div id="login-form">
    <form action="<?php echo $this->url('adminUser', array('action' => 'login')) ?>" method="post">
        <div>
            <input type="text" name="login" class="std-input full-width" placeholder="Логин">
        </div>
        <div>
            <input type="password" name="password" class="std-input full-width" placeholder="Пароль">
        </div>
        <div class="error">Неверное имя пользователя или пароль</div>
        <div class="btn-box">
            <input type="submit" value="Войти" class="btn bg-color">
        </div>
    </form>

    <div class="remind">
        <a href="<?php echo $this->url('adminUser', array('action' => 'remind')) ?>">Непомню пароль :3</a>
    </div>
</div>

<script>
$(function(){
    var form = $('form', '#login-form');

    form.submit(function(){
        $.ajax({
            url: form.attr('action'),
            type: form.attr('method'),
            dataType: 'json',
            data:form.serializeArray(),
            success: function(resp) {
                if(resp['login']) {
                    $('.error', form).fadeOut(200);
                    location.href = '/admin/';
                } else {
                    $('.error', form).fadeIn(200);
                }
            }
        });

        return false;
    });
});
</script>