<div class="error-page">
    <div class="wrapper">
    <div class="txt">
        <div class="code">404</div>
        страница не найдена
    </div>
    </div>
</div>
<style>
    .error-page .wrapper {
        padding-bottom: 100px;
        margin-top: 140px;
    }

    .error-page .pic img {
        max-height: 100%;
    }

    .error-page .txt {
        text-align: center;
        font-size: 25px;
        font-weight: 600;
    }

    .error-page .code {
        font-size: 150px;
    }

    .error-page {

    }
</style>
