<?php if(\User\Service\AuthService::getUser()) { ?>
<script> location.href = "/user/";</script>
<?php } else { ?>

<?php if(!$isAjax) { ?>
<div class="block">
    <div class="wrapper">
<?php } ?>
<div class="popup-box popup-login">
    <div class="header">
        <div class="title">Вход на сайт</div>
    </div>
    <div class="body std-form">
        <?php
        $form
            ->setAttribute('action', $this->url('user', array('action' => 'login')))
            ->setAttribute('class', 'std-form')
            ->setAttribute('id', 'login-form')
            ->setAttribute('method', 'post');

        $form->get('login')
            ->setAttribute('class', 'std-input')
            ->setAttribute('placeholder', 'Электронная почта');

        $form->get('password')
            ->setAttribute('class', 'std-input')
            ->setAttribute('placeholder', 'Пароль');
        ?>

        <?php echo $this->form()->openTag($form); ?>
            <div class="form-box">
                <div class="form-errors"></div>

                <div class="row">
                    <?php echo $this->formElement($form->get('login')) ?>
                </div>

                <div class="row">
                    <?php echo $this->formElement($form->get('password')) ?>
                </div>

                <button class="btn login">Войти на сайт</button>

                <a href="/registration/" class="registration">Создать профиль пользователя</a>

                <a href="/remind/" class="remind">Забыли ваш пароль?</a>
            </div>
            <div class="success-box">
                <i class="fa fa-spinner fa-spin"></i>
            </div>
        <?php echo $this->form()->closeTag($form); ?>

        <div class="soc-block">
            <a class="btn vk" href="<?php echo $socAdapters['vk']->getAuthUrl() ?>"><i class="fab fa-vk"></i></a>
            <a class="btn fb" href="<?php echo $socAdapters['facebook']->getAuthUrl() ?>"><i class="fab fa-facebook-f"></i></a>
            <a class="btn go" href="<?php echo $socAdapters['google']->getAuthUrl() ?>"><i class="fab fa-google-plus-g"></i></a>
            <?php /*
            <a class="ya" href="<?php echo $socAdapters['yandex']->getAuthUrl() ?>"></a>
            <a class="od" href="<?php echo $socAdapters['odnoklassniki']->getAuthUrl() ?>"></a>
            <a class="ma" href="<?php echo $socAdapters['mailru']->getAuthUrl() ?>"></a>
            */ ?>
            <div class="clear"></div>
        </div>
    </div>
</div>
<?php if(!$isAjax) { ?>
    </div>
</div>
<?php } ?>

<script>
	var form = $('#login-form');
	form.formSubmit({
		success: function(resp, form){
			$('.form-box', form).fadeOut(200, function(){
				$('.success-box', form).fadeIn(200);
			});
			location.href="/user/";
		}
	});
</script>
<style>
    .popup-login {
        width: 570px;
        margin: 0 auto;
    }
    .popup-login .body {
        width: 400px;
    }

    .popup-login .std-input {
        text-align: center;
        font-size: 16px;
    }

    .popup-login .login {
        margin-top: 10px;
        width: 100%;
        font-size: 16px;
        height: 45px;
        line-height: 45px;
    }

    .popup-login .registration {
        text-align: center;
        text-transform: uppercase;
        color: #5c5d65;
        font-weight: 700;
        display: block;
        margin-top: 25px;
        letter-spacing: 0.1em;
        transition: all .2s ease;
    }

    .popup-login .registration:hover {
        color: #ee7923;
    }

    .popup-login .remind {
        display: block;
        text-align: center;
        font-size: 16px;
        margin-top: 15px;
        color: #5c5d65;
    }

    .popup-login .soc-block {
        margin-top: 45px;
        margin-bottom: 40px;
    }
    
    .popup-login .soc-block .btn {
        border-radius: 99px;
        height: 50px;
        line-height: 50px;
        font-size: 18px;
        text-align: center;
        display: block;
        background: #3b5998;
        box-shadow: inset 0 0 0 2px #3b5998;
        float: left;
        width: 30%;
        margin-right: 3%;
        color: #ffffff;
    }

    .popup-login .soc-block .btn i {
        margin: 0;
    }

    .popup-login .soc-block .btn.vk {
        background: #3383c1;
        box-shadow: inset 0 0 0 2px #3383c1;
    }

    .popup-login .soc-block .btn.go {
        background: #df4a32;
        box-shadow: inset 0 0 0 2px #df4a32;
    }

    .popup-login .soc-block .btn:hover {
        background: #ffffff;
        color: #3b5998;
        box-shadow: inset 0 0 0 2px #3b5998;
    }

    .popup-login .soc-block .btn.vk:hover {
        background: #ffffff;
        color: #3383c1;
        box-shadow: inset 0 0 0 2px #3383c1;
    }

    .popup-login .soc-block .btn.go:hover {
        background: #ffffff;
        color: #df4a32;
        box-shadow: inset 0 0 0 2px #df4a32;
    }

    /*
    .popup-login .header {
        text-align: center;
    }

    .popup-login .row {
        margin-bottom: 10px;
        position: relative;
    }

    .popup-login .row-btns {
        margin-top: 20px;
        position: relative;
    }

    .popup-login .row .remind {
        position: absolute;
        right: 11px;
        top: 12px;
    }

    .popup-login .row-btns .btn {
        padding: 0 16px;
        display: block;
        float: left;
    }

    .popup-login .row-btns .btn-login {
        margin-right: 3%;
        width: 37%;
    }

    .popup-login .row-btns .btn-registration {
        width: 60%;
    }

    .popup-login .soc-block {
        border-top: 1px solid #d2d2d2;
        padding-bottom: 10px;
    }

    .popup-login .soc-block .header {
        border: none;
        margin-bottom: auto;
    }

    .popup-login .soc-block .list {
        text-align: center;
    }
    
    .popup-login .soc-block .list a {
        display: inline-block;
        background: url('/images/social-log.png');
        width: 34px;
        height: 34px;
        transition: all ease .2s;
        margin: 0 5px;
    }
    .popup-login .soc-block .list a:last-child {
        margin-right: 0;
    }

    .popup-login .soc-block a.vk {
        background-position: 0 0;
    }

    .popup-login .soc-block a.fb {
        background-position: -34px 0;
    }

    .popup-login .soc-block a.ma {
        background-position: -68px 0;
    }

    .popup-login .soc-block a.od {
        background-position: -102px 0;
    }

    .popup-login .soc-block a.go {
        background-position: -136px 0;
    }

    .popup-login .soc-block a.ya {
        background-position: -170px 0;
    }

    .popup-login .soc-block a.vk:hover {
        background-position: 0 -34px;
    }

    .popup-login .soc-block a.fb:hover {
        background-position: -34px -34px;
    }

    .popup-login .soc-block a.ma:hover {
        background-position: -68px -34px;
    }

    .popup-login .soc-block a.od:hover {
        background-position: -102px -34px;
    }

    .popup-login .soc-block a.go:hover {
        background-position: -136px -34px;
    }

    .popup-login .soc-block a.ya:hover {
        background-position: -170px -34px;
    }*/
</style>
<?php } ?>