<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php $form = $this->editForm ?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="images">Картинки</div>
            <div class="tab" data-tab="types">Теги и связи</div>
            <div class="tab" data-tab="seo">SEO</div>
            <div class="tab" data-tab="text">Текст</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->adminFormRow($form->get('image-image'));
                echo $this->adminFormRow($form->get('name'));
                echo $this->adminFormRow($form->get('url'));
                echo $this->adminFormRow($form->get('level'));
                echo $this->adminFormRow($form->get('rating'));
                echo $this->adminFormRow($form->get('video_male'));
                echo $this->adminFormRow($form->get('video_female'));
                ?>
            </div>
            <div class="tab" data-tab="images">
                <?php
                echo $this->adminFormRow($form->get('images-images'));
                ?>
            </div>
            <div class="tab" data-tab="types">
                <?php echo  $this->AdminFormRow($form->get('types-collection')); ?>
                <?php echo  $this->AdminFormRow($form->get('recommended-collection')); ?>
            </div>
            <div class="tab" data-tab="seo">
                <div class="separator">Мужчины</div>
                <?php
                echo $this->adminFormRow($form->get('title_male'));
                echo $this->adminFormRow($form->get('description_male'));
                ?>
                <div class="separator">Женщины</div>
                <?php
                echo $this->adminFormRow($form->get('title_female'));
                echo $this->adminFormRow($form->get('description_female'));
                ?>
            </div>
            <div class="tab" data-tab="text">
                <?php
                echo $this->adminFormRow($form->get('text'));
                ?>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>