<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php
$form = $this->editForm;
$call = $this->model;
$phone = $call->getPlugin('phone');
?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">

                <div class="row">
                    <div class="label">Телефон</div>
                    <a href="<?php echo $phone->getEditUrl() ?>"><?php echo $phone->get('phone') ?></a>
                    <?php echo $phone->get('confirmed') ? '<span class="wrap green">Подтвержден</span>' : '<span class="wrap red">Не подтвержден</span>' ?>
                </div>

                <?php
                $html = '<div class="row">';

                switch($call->get('type_id')) {
                    case \CallcenterAdmin\Model\Call::TYPE_REQUEST:
                        $product = $call->getPlugin('item')->getPlugin('product');
                        echo
                        '<div class="row">'
                            .'<div class="label">Товар</div>'
                            .'<a href="' . $product->getEditUrl() . '">' . $product->get('name') . '</a> (' . $product->get('size') . ' - ' . $product->get('taste') . ')'
                        .'</div>';
                        break;
                    case \CallcenterAdmin\Model\Call::TYPE_ORDER:
                        $order = $call->getPlugin('item');
                        echo
                            '<div class="row">'
                                .'<div class="label">Заказ</div>'
                                .'<a href="' . $order->getEditUrl() . '">№' . $order->getId() . '</a>'
                            .'</div>';
                        break;
                    case \CallcenterAdmin\Model\Call::TYPE_RETURN:
                        $order = $call->getPlugin('item');
                        echo
                            '<div class="row">'
                                .'<div class="label">Заказ</div>'
                                .'<a href="' . $order->getEditUrl() . '">№' . $order->getId() . '</a>'
                            .'</div>';
                        break;
                }
                ?>

                <?php
                echo $this->AdminFormRow($form->get('name'));
                echo $this->AdminFormRow($form->get('theme'));
                echo $this->AdminFormRow($form->get('desc')); ?>

                <div class="row">
                    <div class="label">Статус</div>
                    <?php echo $call->get('status') ?
                        '<span>' . \CallcenterAdmin\Model\Call::$statuses[$call->get('status')] . '</span>'
                        :
                        '<div class="status-box"><span class="btn btn-green btn-status" data-status="' . \CallcenterAdmin\Model\Call::STATUS_COMPLETE . '">Выполнена</span>'
                        .' <span class="btn btn-red btn-status" data-status="' . \CallcenterAdmin\Model\Call::STATUS_REJECT . '">Отклонена</span></div>' ?>
                </div>

                <?php echo $this->AdminFormRow($form->get('type_id')); ?>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>

<script>
    var form = $('.edit-form');

    $('.btn-status', form).on('click', function () {
        var btn = $(this);

        $.ajax({
            url: '/admin/callcenter/callcenter/complete/',
            data: {
                id: '<?php echo $call->getId() ?>',
                status: btn.data('status')
            },
            method: 'post',
            success: function(resp) {
                $('.status-box', form).after('<span>Статус изменен</span>');
                $('.status-box', form).remove();
            }
        });
    });
</script>

<style>
    .edit-form .btn-complete {
        text-align: center;
    }

    .edit-form .status-box {
        display: inline-block;
    }
</style>