<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php
$form = $this->editForm;
$module = $this->model->getPlugin('module');
?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="seo">SEO</div>
            <div class="tab" data-tab="text">Текст</div>
            <div class="tab" data-tab="content">Текст страницы</div>
        </div>
        <div class="tabs-body">
            <?php if($module->getId()) {
                $moduleUrl = $this->url('admin', array('module' => $module->get('module'), 'section' => $module->get('section')));
            ?>
                <div class="notice">
                    Эта страница относится к модулю "<a href=""><?php echo $this->model->getPlugin('module')->get('name') ?></a>" и не может быть удалена.<br>
                    Также для страниц модулей достуны не все настройки.
                </div>
            <?php } ?>


            <div class="tab" data-tab="general">
                <?php
                echo $this->AdminFormRow($form->get('name'));
                echo $this->AdminFormRow($form->get('header'));
                echo $this->AdminFormRow($form->get('image-image'));
                echo $this->AdminFormRow($form->get('url'));
                echo $this->AdminFormRow($form->get('redirect_url'));
                echo $this->AdminFormRow($form->get('parent'));
                echo $this->AdminFormRow($form->get('layout'));
                ?>
            </div>
            <div class="tab" data-tab="seo">
                <?php
                echo $this->AdminFormRow($form->get('title'));
                echo $this->AdminFormRow($form->get('keywords'));
                echo $this->AdminFormRow($form->get('description'));
                ?>
            </div>
            <div class="tab" data-tab="text">
                <?php
                echo $this->AdminFormRow($form->get('text'));
                ?>
            </div>
            <div class="tab" data-tab="content">
                <?php if($this->model->getId()) {
                    $parentModule = $this->model;

                    echo $this->adminTableList($this->contentItemsFields, $this->contentItems, array(
                        'module'  => 'application',
                        'section' => 'content',
                        'buttons' => array(
                            'edit'   => function($model, $view) use ($parentModule) {
                                $editUrl = $view->url('admin',
                                    array(
                                        'module' => 'application',
                                        'section' => 'content',
                                        'action' => 'edit'),
                                    array('query' => array('id' => $model->getId(), 'parent' => $parentModule->getId(), 'module' => 'application', 'route' => 'adminPage'))
                                );
                                return '<a class="btn btn-green edit" href="' . $editUrl . '"><i class="fa fa-pencil-square-o"></i> Просмотр</a>';
                            },
                        ),
                    ));

                    $addUrl = $this->url('adminContentItems', array(
                        'action' => 'edit'
                    ), array(
                        'query' => array('parent' => $this->model->getId(), 'module' => 'application', 'route' => 'adminPage')
                    ));
                    ?>
                    <div style="margin-top: 10px;">
                        <a href="<?php echo $addUrl ?>" class="btn btn-blue">Добавить</a>
                    </div>
                <?php } else { ?>
                    <div class="notice">
                        Возможность редактирования контента появиться после первого сохранения.
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <a class="btn btn-gray" href="<?php echo $this->url('admin', array('module' => $this->engine->module->get('module'), 'section' => $this->engine->module->get('section'))) ?>">
            <i class="fa fa-reply"></i>
            Вернутся
        </a>
        <?php if($model->getId() && !$model->get('module_id')) { ?>
        <a class="btn btn-red btn-remove-ck" href="#popup-delete">
            <i class="fa fa-times"></i>
            Удалить
        </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>