<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php $form = $this->editForm ?>
<?php echo $this->form()->openTag($form) ?>

<div class="panel">
    <?php $url = '/blog/article/' . $model->get('url') . '/'; ?>
    <a href="<?php echo $url ?>" target="_blank">Показать на сайте</a>

</div>

<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="types">Типы и теги</div>
            <div class="tab" data-tab="seo">SEO</div>
            <div class="tab" data-tab="links">Ссылки</div>
            <div class="tab" data-tab="content">Текст</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->AdminFormRow($form->get('image-image'));
                echo $this->AdminFormRow($form->get('name'));
                echo $this->AdminFormRow($form->get('blog_id'));
                echo $this->AdminFormRow($form->get('tags'));
                echo $this->AdminFormRow($form->get('hits'));
                echo $this->AdminFormRow($form->get('preview'));
                echo $this->AdminFormRow($form->get('time_create'));
                echo $this->AdminFormRow($form->get('url'));
                ?>
            </div>
            <div class="tab" data-tab="types">
                <?php echo  $this->AdminFormRow($form->get('types-collection')); ?>
            </div>
            <div class="tab" data-tab="seo">
                <?php
                echo $this->AdminFormRow($form->get('title'));
                echo $this->AdminFormRow($form->get('description'));
                ?>
            </div>

            <div class="tab" data-tab="content">
                <a href="/admin/application/content/edit/?module=blog&depend=<?php echo $model->getId() ?>" class="btn popup-form">Добавить</a>
                <?php echo $this->adminContentList($model->getPlugin('content')); ?>
            </div>
        </div>
    </div>

    <script>
        $(function() {
            var list = $('.content-list');

            $('.del', list).on('click', function() {
                var el = $(this);
                $.ajax({
                    url: '/admin/application/content/delete/',
                    method: 'post',
                    data: {id: el.data('id')},
                    success: function() {
                        el.closest('.item').remove();
                    }
                });
            });
        });
    </script>

    <style>
        .content-list .item {
            background: #f2f2f2;
            border-radius: 2px;
            padding: 10px 10px 5px 10px;
            margin-top: 15px;
            max-width: 900px;
        }

        .content-list .text {
            position: relative;
            margin-bottom: 10px;
            max-height: 100px;
            overflow: hidden;
        }

        .content-list .text:after {
            content: '';
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 70px;
            background: linear-gradient(transparent, #f2f2f2);
        }

        .content-list .pics .pic {
            width: 120px;
            margin: 0 6px 6px 0;
            float: left;
        }

        .content-list .btns {
            margin-bottom: 5px;
        }

        .content-list .btns a {
            display: inline-block;
            margin-right: 10px;
            cursor: pointer;
        }
    </style>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>