<div class="block">
    <div class="wrapper">
        <?php
        $adapterConfigs = array(
            'vk' => array(
                'client_id'     => '5477096',
                'client_secret' => 'pv8S0LnX7tQu6gfHzkKL',
                'redirect_uri'  => 'https://olympic-trade.ru/tests/'
            ),
            'odnoklassniki' => array(
                'client_id'     => '',
                'client_secret' => '',
                'redirect_uri'  => 'http://localhost/auth?provider=odnoklassniki',
                'public_key'    => 'CBADCBMKABABABABA'
            ),
            'mailru' => array(
                'client_id'     => '',
                'client_secret' => '',
                'redirect_uri'  => 'http://localhost/auth/?provider=mailru'
            ),
            'yandex' => array(
                'client_id'     => '',
                'client_secret' => '',
                'redirect_uri'  => 'http://localhost/auth/?provider=yandex'
            ),
            'google' => array(
                'client_id'     => '',
                'client_secret' => '',
                'redirect_uri'  => 'http://localhost/auth?provider=google'
            ),
            'facebook' => array(
                'client_id'     => '',
                'client_secret' => '',
                'redirect_uri'  => 'http://localhost/auth?provider=facebook'
            )
        );

        $adapters = array();

        foreach ($adapterConfigs as $adapter => $settings) {
            $class = 'SocialAuther\Adapter\\' . ucfirst($adapter);
            $adapters[$adapter] = new $class($settings);
        }

        $auther = new \SocialAuther\SocialAuther($adapters['vk']);
		
		/*if ($auther->authenticate()) {
			echo '<pre>';
			var_dump([
				'provider'  => $auther->getProvider(),
				'socialId'  => $auther->getSocialId(),
				'name' 		=> $auther->getName(),
				'email' 	=> $auther->getEmail(),
				'socialPage' => $auther->getSocialPage(),
				'sex' 		=> $auther->getSex(),
				'birthday' 	=> $auther->getBirthday(),
				'avatar' 	=> $auther->getAvatar(),
			]);
			echo '</pre>';
		}*/
        ?>

        <?php


        /*if (isset($_SESSION['user'])) {
            echo '<p><a href="info.php">Скрытый контент</a></p>';
        } else if (!isset($_GET['code']) && !isset($_SESSION['user'])) {*/
        foreach ($adapters as $title => $adapter) {
            echo '<p><a href="' . $adapter->getAuthUrl() . '">Аутентификация через ' . ucfirst($title) . '</a></p>';
        }
        //}
        ?>
    </div>
</div>