<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            body {
                background: #ebebeb;
            }

            .wrapper {
                max-width: 1200px;
                min-width: 960px;
                background: #ffffff;
                padding: 10px 20px;
                margin: 10px auto 10px auto;
                border: 1px solid #c3c3c3;
                word-wrap: break-word;
            }
        </style>
    </head>
    <body>
        <div class="wrapper">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>