<?php $this->headLink()->prependStylesheet('/modules/news/css/main.css') ?>
<div class="main-header">
    <div class="box">
        <h1>Новости</h1>
        <?php echo $this->breadcrumbs($breadcrumbs, ' <i class="fa fa-chevron-right"></i> ') ?>
    </div>
</div>

<div class="block">
    <div class="wrapper">
        <div class="news-list">
            <?php echo $this->newsList($news) ?>
        </div>
    </div>
</div>