<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>

    <?php
    $settingsUrl = $this->url('admin', array(
        'module' => $this->engine->module->get('module'),
        'section' => $this->engine->module->get('section'),
        'action' => 'settings'
    ));
    ?>
    <a href="<?php echo $settingsUrl ?>" class="module-config"><i class="fa fa-cog"></i></a>
</h1>

<?php
$form = $this->editForm;
$catalog = $this->model;
?>
<?php echo $this->form()->openTag($form) ?>

<div class="panel">
    <?php $url = '/catalog/' . $catalog->get('url_path') . '/'; ?>
    <a href="<?php echo $url ?>" target="_blank">Показать на сайте</a>

    <?php
        $url = $this->url('adminProducts', array('action' => 'list')) . '?catalog_id=' . $catalog->getId(); ?>
        | <a href="<?php echo $url ?>">Товары</a>
</div>

<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="seo">SEO</div>
            <div class="tab" data-tab="types">Типы</div>
            <div class="tab" data-tab="props">Свойства</div>
            <div class="tab" data-tab="content">Описание</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->AdminFormRow($form->get('image-image'));
                echo $this->AdminFormRow($form->get('name'));
                echo $this->AdminFormRow($form->get('short_name'));
                echo $this->AdminFormRow($form->get('active'));
                echo $this->AdminFormRow($form->get('url'));
                echo $this->AdminFormRow($form->get('parent'));
                ?>
            </div>
            <div class="tab" data-tab="seo">
                <?php
                echo $this->AdminFormRow($form->get('header'));
                echo $this->AdminFormRow($form->get('title'));
                echo $this->AdminFormRow($form->get('description'));
                ?>
            </div>
            <div class="tab" data-tab="types">
                <?php echo $this->formRow($form->get('types-collection')); ?>
            </div>
            <div class="tab" data-tab="props">
                <?php echo $this->formRow($form->get('props-collection')); ?>
            </div>
            <div class="tab" data-tab="content">
                <?php echo $this->formRow($form->get('text')); ?>
                <?php /*if($this->model->getId()) {
                    $parentModule = $this->model;

                    echo $this->adminTableList($this->contentItemsFields, $this->contentItems, array(
                        'module'  => 'application',
                        'section' => 'content',
                        'buttons' => array(
                            'edit'   => function($model, $view) use ($parentModule) {
                                $editUrl = $view->url('admin',
                                    array(
                                        'module' => 'application',
                                        'section' => 'content',
                                        'action' => 'edit'),
                                    array('query' => array('id' => $model->getId(), 'parent' => $this->model->getId(), 'module' => 'catalog', 'route' => 'adminCatalog'))
                                );
                                return '<a class="btn btn-green edit" href="' . $editUrl . '"><i class="fa fa-pencil-square-o"></i> Просмотр</a>';
                            },
                        ),
                    ));
                ?>

                    <?php
                    $addUrl = $this->url('adminContentItems', array(
                        'action' => 'edit'
                    ), array(
                        'query' => array('parent' => $this->model->getId(), 'module' => 'catalog', 'route' => 'adminCatalog')
                    ));
                    ?>
                    <div style="margin-top: 10px;">
                        <a href="<?php echo $addUrl ?>" class="btn btn-blue">Добавить</a>
                    </div>
                <?php } else { ?>
                    <div class="notice">
                        Возможность редактирования контента появиться после первого сохранения.
                    </div>
                <?php }*/ ?>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>

<script>
    $(function() {
        $('[name="title"], [name="description"]').each(function () {
            var input = $(this);
            var counter = $('<span class="desc-counter"></span>');
            counter.insertAfter(input);

            input.on('keyup', function () {
                counter.text($(this).val().length);
            }).trigger('keyup');
        });
    });
</script>