<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php
$form = $this->editForm;
$supply = $this->model;
?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <?php if($supply->getId()) { ?>
            <div class="tab" data-tab="cart">Товары</div>
            <?php } ?>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->AdminFormRow($form->get('number'));
                echo $this->AdminFormRow($form->get('user_id'));
                echo $this->AdminFormRow($form->get('login'));
                echo $this->AdminFormRow($form->get('weight'));
                echo $this->AdminFormRow($form->get('delivery'));
                echo $this->AdminFormRow($form->get('date'));
                echo $this->AdminFormRow($form->get('currency_rate'));
                echo $this->AdminFormRow($form->get('desc'));
                ?>
            </div>
            <div class="tab" data-tab="cart">
                <?php echo $this->adminSupplyCart($supply) ?>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>

<style>
    .supply-table tfoot td {
        vertical-align: top;
        padding-top: 15px;
    }

    .supply-table .cart-price {
        width: 80px;
        margin: 0 10px;
        border-radius: 0;
        height: 28px;
        border: 1px solid #cecece;
    }

    .supply-table .fade {
        display: none;
    }
</style>

<script>
    var cTable = $('.supply-table');
    var cPrice = $('.cart-price', cTable);
    var cCount = $('.cart-count', cTable);
    var cDel   = $('.cart-del', cTable);
    var productForm = $('.product-form');

    $('.check', cTable).on('click', function () {
        $(this).closest('tr').toggleClass('fade');
    });

    var cPriceTimer;
    cPrice.on('keyup', function () {
        var el = $(this);
        clearTimeout(cPriceTimer);
        cPriceTimer = setTimeout(function() {
            $.ajax({
                url: '/admin/catalog/supplies/cart-update/',
                data: {
                    cartId:  el.data('id'),
                    price:   el.val(),
                    type:   'price'
                },
                method: 'post',
                success: function(resp) {
                    $('.supply-price', cTable).text($.aptero.price(resp.price));
                }
            });
        }, 400);
    });

    cCount.on('change', function () {
        var el = $(this);
        $.ajax({
            url: '/admin/catalog/supplies/cart-update/',
            data: {
                cartId: el.data('id'),
                count:  el.val(),
                type:   'count'
            },
            method: 'post',
            success: function(resp) {
                el.closest('tr').find('.pr-stock span').text($.aptero.price(resp.stock));
            }
        });
    });

    cDel.on('click', function () {
        var el = $(this);
        $.ajax({
            url: '/admin/catalog/supplies/cart-update/',
            method: 'post',
            data: {
                supplyId: <?php echo $supply->getId() ?>,
                cartId:  el.data('id'),
                count:   -1,
                type:   'count'
            },
            success: function(resp) {
                el.closest('tr').remove();
            }
        });
    });

    function loadProductParams(id) {
        $.ajax({
            url: '/admin/catalog/products/get-size-taste/',
            method: 'post',
            data: {
                productId: id
            },
            success: function(resp) {
                var html = '';

                html +=
                    '<div class="row">' +
                    renderElement('select', {
                        options: resp.size,
                        class:   'std-select size'
                    }) +
                    '</div>' +
                    '<div class="row">' +
                    renderElement('select', {
                        options: resp.taste,
                        class:   'std-select taste'
                    }) +
                    '</div>' +
                    '<div class="row">' +
                    renderElement('text', {
                        class:   'std-input count',
                        placeholder: 'Кол-во',
                        value: 1
                    }) +
                    '</div>'+
                    '<div class="row">' +
                    renderElement('text', {
                        class:   'std-input price',
                        placeholder: 'Стоимость'
                    }) +
                    '</div>';

                $('.props', productForm).html(html);
            }
        });
    }

    $('.product-form .product').on('keyup', function () {
        $('.props', productForm).empty();
    });

    $('.product-form .product').autocomplete({
        source: function( request, response ) {
            $.ajax( {
                url: "/admin/catalog/products/autocomplete/",
                dataType: "json",
                method: 'post',
                data: {
                    query: request.term
                },
                success: function(data) {
                    response(data);
                }
            });
        },
        select: function( event, ui ) {
            loadProductParams(ui.item.id);
        }
    });

    $('.btn', productForm).on('click', function () {
        if(!$('.row', $('.props', productForm)).length) {
            alert('Товар не выбран');
            return false;
        }

        $.ajax( {
            url: "/admin/catalog/supplies/add-product/",
            dataType: "json",
            method: 'post',
            data: {
                supplyId: <?php echo $supply->getId() ?>,
                product: $('.product', productForm).val(),
                tasteId: $('.taste', productForm).val(),
                sizeId:  $('.size', productForm).val(),
                count:   $('.count', productForm).val(),
                price:   $('.price', productForm).val()
            },
            success: function(data) {
                $('.props', productForm).empty();
                $('.product', productForm).val('');

                location.href = '/admin/catalog/supplies/edit/?id=<?php echo $supply->getId() ?>#edit-tabs=cart';
                location.reload();
            }
        });
    });
</script>