<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Штрихкоды</title>
        <link href="/engine/images/favicon.png" rel="shortcut icon">
		<link href="/engine/css/reset.css" media="screen" rel="stylesheet" type="text/css">
		
		<style>
			.code {
				float: left;
				padding: 20px 0 30px 0;
				border: 1px solid #efefef;
				text-align: center;
				width: 25%;
				-webkit-box-sizing: border-box;
				-moz-box-sizing: border-box;
				box-sizing: border-box;
				margin: 0 -1px -1px 0 ;
			}

			.code .row {
				font-size: 14px;
				margin-bottom: 2px;
				font-family: "Arial", sans-serif;
			}

			.code img {
				margin-top: 12px;
			}
		</style>
    </head>
    <body>

	<?php echo $this->adminBarcodes($orders) ?>
	
	<script>
		window.print();
	</script>

    </body>
</html>