<?php
$exportDate = (new \DateTime())->modify('+1 day');
?>

<div class="popup-box popup-order-ex">
    <div class="header">
        Отправка заказов
    </div>
    <div class="body">
		<div class="controls">
			<?php /*<span class="btn" data-type="export">Заказать забор</span>
			<span class="btn popup-form" href="/admin/catalog/orders/stock/">Сбор заказов</span>*/ ?>
			<span class="btn popup-form" href="/admin/catalog/orders/order-index-express/">Index Express</span>
			<span class="btn popup-form" href="/admin/catalog/orders/order-glavpunkt/">Главпункт</span>
			<?php /*<span class="btn" data-type="st-collected-sl">Cтатус "Собран" SL</span>*/ ?>
			<span class="btn" data-type="st-delivery">Cтатус "В доставке"</span>
			<div class="clear"></div>
		</div>
		
		<div class="options">
			<div class="box" data-type="export">
				<div class="row row-date">
					<div class="label">Дата забора</div>
					<input type="text" class="datepicker export-date" value="<?php echo $exportDate->format('Y-m-d'); ?>">
					<input type="submit" class="btn submit" value="Отправить">
				</div>
			</div>
		</div>
		
		<div class="console"></div>
    </div>

    <script>
		$(function() {
			var ids = [];
			$('.table-list .tb-cb:checked').each(function() {ids.push($(this).val());});
			
			var popup = $('.popup-order-ex');
			var controls = $('.controls', popup);
			var options = $('.options', popup);
			var sConsole = $('.console', popup);
			
			iniDatepicker(popup);
			
			function consoleLoading() {
				sConsole.html('<div class="loading"><i class="fa fa-spin fa-refresh"></i></div>');
			}
			
			function consoleRender(rows) {
				var html = '';
								
				$.each(rows, function(key, val) {
					html += 
					'<div class="row">' +
						'<div class="id">' + key + ':</div>';
						
					if(val) {
						html += '<div class="status error">' + val + '</div>';
					} else {
						html += '<div class="status ok">Успех</div>';
					}
					
					html +=
						'</div>';
				});
				
				sConsole.empty().html(html);
			}
			
			$('.btn', controls).on('click', function() {
				var btn = $(this);
				$('.box', options).css({display: 'none'});
				sConsole.empty();
				
				/*if(btn.data('type') == 'codes') {
					window.open('/admin/catalog/orders/barcodes/?ids[]=' + ids.join('&ids[]='), '_blank');
				}*/
				
				if(btn.data('type') == 'export') {
					$('.box[data-type="export"]', options).css({display: 'block'});
				}

				/*
				if(btn.data('type') == 'st-collected-sl') {
					consoleLoading();

					$.ajax({
						url: '/admin/catalog/orders/status-collected-sl/',
						method: 'post',
						data: {
						    ids: ids,
                            type: 2
                        },
						dataType: 'json',
						success: function(resp) {
							consoleRender(resp.rows);
						}
					});
				}
				*/
				if(btn.data('type') == 'st-delivery') {
					consoleLoading();
				
					$.ajax({
						url: '/admin/catalog/orders/set-status-delivery/',
						method: 'post',
						data: {ids: ids},
						dataType: 'json',
						success: function(resp) {
							consoleRender(resp.rows);
						}
					});
				}
			});
			
			//Export
			$('.box[data-type="export"] .submit', options).on('click', function() {
				var options = $('.box[data-type="export"]');
				consoleLoading();
				
				$.ajax({
					url: '/admin/catalog/orders/orders-export/',
					method: 'post',
					data: {
						ids: ids,
						date: $('.export-date', options).val(),
					},
					dataType: 'json',
					success: function(resp) {
						consoleRender(resp.rows);
					},
				});
			});
		});

    </script>
	
    <style>
        .popup-order-ex .controls {
			width: 415px;
		}
        .popup-order-ex .options .box {
			display: none;
		}
		
        .popup-order-ex .controls .btn {
            display: block;
			width: 49%;
			margin: 0 2% 7px 0;
			float: left;
        }
		
        .popup-order-ex .controls .btn:nth-child(2n) {
			margin-right: 0;
		}

        .popup-order-ex .row-date .label {
            position: absolute;
            width: 100px;
            line-height: 30px;
            left: 0;
            top: 0;
        }

        .popup-order-ex .row-date {
			position: relative;
            padding-left: 100px;
			margin-bottom: 10px;
        }

        .popup-order-ex .row label {
            display: block;
            margin-bottom: 6px;
        }
		
        .popup-order-ex .console {
			border-radius: 2px;
			border: 1px solid #eee;
			padding: 2px 5px;
		}

        .popup-order-ex .console .row {
			position: relative;
			font-size: 13px;
			padding: 3px 0 3px 45px;
			border-bottom: 1px solid #eee;
        }

        .popup-order-ex .console .row:last-child {
			border-bottom: none;
		}

        .popup-order-ex .console .row .id {
			position: absolute;
			left: 0;
        }

        .popup-order-ex .console .error {
			color: red;
        }

        .popup-order-ex .console .ok {
			color: green;
        }

        .popup-order-ex .console .loading {
			text-align: center;
			font-size: 20px;
			padding: 10px;
        }
    </style>
</div>