<?php $domain = 'http://' . $_SERVER['HTTP_HOST']; ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <meta charset="UTF-8">
    <title>Olympic</title>
    <style>
        * {
            padding: 0;
            margin: 0;
            font-family: 'Helvetica', sans-serif;
        }
        
        h3 {
            padding: 20px 0 10px 0;
        }

        p {
            padding: 0 0 10px 0;
        }

        hr {
            margin: 15px 0 8px 0;
        }
    </style>
</head>
<body style="padding: 0; margin: 0;">

<table border="0" cellpadding="0" width="100%" cellspacing="0" style="background: #f1f1f1; margin:0 auto; padding:0; ">
    <tr>
        <td style="padding: 20px 10px">
            <table border="0" cellpadding="0" width="100%" cellspacing="0" style="background: #485361; margin:0 auto; padding:0; max-width: 1300px; min-width: 400px;">
                <tr>
                    <td style="padding: 10px; background: #0060c1; vertical-align: top; border-radius: 5px;">
                        <table border="0" cellpadding="0" width="100%" cellspacing="0" style="margin:0; padding:0; width: 100%;">
                            <tr>
                                <td style="background-color: #ffffff; border-radius: 5px 5px 0 0;">
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="width: 100%;">
                                        <tr>
                                            <td style="padding: 20px"><?php echo $this->content; ?></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>
