<tr><td style="padding: 0 20px">
    <table style="min-width: 250px; margin: 0 auto; font-size: 14px;"><tbody>

    <tr><td colspan="2" height="20" style="height: 20px;"></td></tr>

    <tr>
        <td colspan="2" width="100%" style="padding-bottom: 6px; text-align: center">
            <span class="header">Восстановление пароля</span>
        </td>
    </tr>

    <tr><td colspan="2" height="20" style="height: 10px;"></td></tr>

    <tr><td colspan="2" style="text-align: center;">
        <a href="http://<?php echo $this->confirmLink ?>" class="btn">Обновить пароль</a>
    </td></tr>

    <tr><td colspan="2" height="20" style="height: 20px;"></td></tr>

    </tbody></table>
</td></tr>